### PR TITLE
Categorise commonmark library

### PR DESCRIPTION
**Pull request by mscharley**
Not sure what the standard for this repo is, but this is still prerelease strictly speaking, but progressing well so kicking this off early as things take time to merge.

### CODE REVIEW

**Comment by lpil** [comment]
Sweet! How about we put this in text as while it is implemented using parsing it is not used for parsing?

**Comment by mscharley** [comment]
It's arguably both - you can render out to HTML directly, you can parse into an AST (hayleigh plans to use this to render out to lustre components instead of the raw html mode), or one unstarted featured that I was considering but would be useful for this repo is generating an AST programmatically then rendering it out to markdown.

I don't have a strong opinion, especially if we can only pick one.

**Comment by mscharley** [comment]
There's also a pretty strong argument for it to go in a new `Templating` group along with things like Pug.

**Comment by lpil** [comment]
Let's go for "File Formats" as there's other AST producing parsers there

**Comment by mscharley** [comment]
@lpil done!

**Review by lpil — APPROVED** [review]
Thanks again!!!

**Pull request merged**
