### PR TITLE
Add 'rada' library to list under 'Time'

### PR DESCRIPTION
**Pull request by michaeljones**
Using the standard config approach.

### CODE REVIEW

**Review by lpil — COMMENTED** [review]
Could you run `gleam run` please 🙏

**Comment by michaeljones** [comment]
I think I have. Is there something you're expecting to see? Should I commit all the extra toml files that are generated in the `packages` folder?

**Comment by lpil** [comment]
Yes, the other configuration files are missing

**Comment by michaeljones** [comment]
Done!

**Review by lpil — APPROVED** [review]
Thank you again!!

**Pull request merged**
