### PR TITLE
Add emel, gleam_synapses, and gleam_zlists

### PR DESCRIPTION
**Pull request by mrdimosthenis**
* Please let me know if you prefer a separate pull request for each package.
* I placed `emel` and `gleam_synapses` under _Data Structures_ instead of introducing a new _Machine Learning_ category. If you think a new category is necessary, I would be happy to add it.

### CODE REVIEW

**Comment by lpil** [comment]
A new ML category sounds cool!

**Comment by mrdimosthenis** [comment]
> I just had a look and it seems like these libraries have not been updated in a long time and likely won't work with current Gleam versions. Have you tested them?

You are right. I will try to update them and get back to you once they work properly with the latest version of Gleam.

**Comment by mrdimosthenis** [comment]
> I just had a look and it seems like these libraries have not been updated in a long time and likely won't work with current Gleam versions. Have you tested them?

@lpil I updated all three libraries and tested them with `gleam-version: "1.5.1"`.

**Review by lpil — APPROVED** [review]
Thank you!!

**Pull request merged**
