### PR TITLE
Added chatter-reborn under web applications

### PR DESCRIPTION
**Pull request by connellr023**
Chatter is a real-time chat web application that demonstrates gleam's ability to take advantage of the actor model when developing concurrent programs.

### CODE REVIEW

**Comment by lpil** [comment]
Hello! CI is failing due to the generated README being edited here

**Comment by connellr023** [comment]
That's understandable. Why was the CI failing? Additionally, could you provide insight on how to use actors better. It's hard to find this information as the language is so new.

**Comment by lpil** [comment]
OTP isn't part of Gleam specifically, so any existing books on it from Erlang or Elixir will teach what you need to know. Elixir in Action and Learn You Some Erlang and Designing for Scale with Erlang/OTP are great books

**Comment by connellr023** [comment]
Ok thanks. I am going to close this and see what I can do.

**Pull request closed without merging**
